input:
  label: ""
  socket_server:
    network: tcp
    address: 0.0.0.0:9998
pipeline:
  processors:
    - mapping: |
        root = this
        root = if this.RECORD_TYPE == 3 { deleted() }
output:
  label: ""
  stdout:
    codec: lines