metrics:
  json_api: {}
  mapping: ""
input:
  label: ""
  socket_server:
    network: tcp
    address: 0.0.0.0:9998
pipeline:
  processors:
    - mapping: |
        root = this
        root = if this.SYS_IND == "T" { deleted() }
    - mapping: |
        root = this
        root.DENIAL_COUNT = if this.RECORD_TYPE == 3 { 1 } else { 0 }
        root.TOTAL_COUNT = 1
output:
  label: ""
  stdout:
    codec: lines